# Generated by Django 4.2.1 on 2023-11-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_alter_patient_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("breathalyzerBatchs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreathalyzerTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("result_breathalyzer_test", models.CharField(max_length=150)),
                ("local_breathalyzer_test", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "breathalyzerBatch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breathalyzerTests",
                        to="breathalyzerBatchs.breathalyzerbatch",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breathalyzerTests",
                        to="patients.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breathalyzerTests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
