# Generated by Django 4.1.7 on 2023-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coren",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tel",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="power_bi_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
