# Generated by Django 4.2.1 on 2023-11-15 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugTestBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("surname_drug_test_batch", models.CharField(max_length=150)),
                ("register_drug_test_batch", models.CharField(max_length=150)),
                ("validity_drug_test_batch", models.CharField(max_length=150)),
                ("method_drug_test_batch", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
