# Generated by Django 4.2.1 on 2023-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drugTestBatchs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugtestbatch",
            name="surname_drug_test_batch",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
