# Generated by Django 4.2.1 on 2023-11-15 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_alter_client_client_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("role", models.CharField(max_length=255)),
                ("date_birth", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("tel", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
