# Generated by Django 4.2.1 on 2023-11-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_client_email_and_more"),
        ("patients", "0002_alter_patient_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="clients.client",
            ),
        ),
    ]
