# Generated by Django 4.1.7 on 2024-01-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="cep",
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_birth",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="role",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="tel",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
