# Generated by Django 4.2.1 on 2023-11-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0002_alter_quiz_patients_alter_quiz_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="patients",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizs",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
