# Generated by Django 4.2.1 on 2023-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizs", "0005_quiz_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="description_consumed_alcoholic",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_consumed_drugs",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description_regular_medication",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
