# Generated by Django 4.2.1 on 2024-01-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizs", "0007_remove_quiz_description_consumed_alcoholic"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="alters_ability_activities",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="change_in_health",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="currently_locomotor_difficulties",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_alters_ability_activities",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_change_in_health",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_currently_locomotor_difficulties",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_noticed_change_concentration",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_noticing_changes_sleep",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_pain_moment",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_recent_changes_mood",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="noticed_change_concentration",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="noticing_changes_sleep",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="pain_moment",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="recent_changes_mood",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
