# Generated by Django 4.1.7 on 2024-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizs", "0009_remove_quiz_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="select_corresponding_unit",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
