# Generated by Django 4.1.7 on 2024-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizs", "0010_quiz_select_corresponding_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="prefer_alters_ability_activities",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_change_in_health",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_consumed_drugs",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_currently_locomotor_difficulties",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_noticed_change_concentration",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_noticing_changes_sleep",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_pain_moment",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_recent_changes_mood",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="prefer_regular_medication",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
