# Generated by Django 4.1.7 on 2024-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizs", "0012_quiz_standard_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="approve_initiative",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
